export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REDUCE_COUNT = "CART_REDUCE_COUNT";
export const CART_INCREASE_COUNT = "CART_INCREASE_COUNT";
