export const ORDER_ITEM_FAIL = "ORDER_ITEM_FAIL";
export const ORDER_ITEM_REQUEST = "ORDER_ITEM_REQUEST";
export const ORDER_ITEM_SUCCESS = "ORDER_ITEM_SUCCESS";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";
export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST";
export const DELETE_ITEMS_SUCCESS = "DELETE_ITEMS_SUCCESS";
export const DELETE_ITEMS_FAIL = "DELETE_ITEMS_FAIL";
export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";

