export const COLLECTION_LIST_GET_REQUEST = "COLLECTION_LIST_GET_REQUEST";
export const COLLECTION_LIST_GET_SUCCESS = "COLLECTION_LIST_GET_SUCCESS";
export const COLLECTION_LIST_GET_FAIL = "COLLECTION_LIST_GET_FAIL";

export const GAME_GET_REQUEST = "GAME_GET_REQUEST";
export const GAME_GET_SUCCESS = "GAME_GET_SUCCESS";
export const GAME_GET_FAIL = "GAME_GET_FAIL";
