export const ADD_NEW_GAME_FAIL = "ADD_NEW_GAME_FAIL";
export const ADD_NEW_GAME_REQUEST = "ADD_NEW_GAME_REQUEST";
export const ADD_NEW_GAME_SUCCESS = "ADD_NEW_GAME_SUCCESS";
export const ADD_NEW_GAME_EMPTY = "ADD_NEW_GAME_EMPTY";
