export const COLLECTION_LIST_GET_REQUEST = "COLLECTION_LIST_GET_REQUEST";
export const COLLECTION_LIST_GET_SUCCESS = "COLLECTION_LIST_GET_SUCCESS";
export const COLLECTION_LIST_GET_FAIL = "COLLECTION_LIST_GET_FAIL";
