export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";
export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_EMPTY = "GET_COMMENTS_EMPTY";


export const POST_COMMENTS_FAIL = "POST_COMMENTS_FAIL";
export const POST_COMMENTS_REQUEST = "POST_COMMENTS_REQUEST";
export const POST_COMMENTS_SUCCESS = "POST_COMMENTS_SUCCESS";