export const USER_LIST_GET_REQUEST = "USER_LIST_GET_REQUEST";
export const USER_LIST_GET_SUCCESS = "USER_LIST_GET_SUCCESS";
export const USER_LIST_GET_FAIL = "USER_LIST_GET_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAIL = "USER_EDIT_FAIL";
